Repository SOEN341Fall2024/TeamXL-SOEN341_Project_F24, pull requests merged in 2024-11, with the labels that each got.

#193 Bug fix/joyal UI- sprint 3
  README.md
  app.js
  uploads/home.jpg
  views/home.ejs
  views/incorrect-pw-un.ejs
  views/instructor-dashboard.ejs
  views/login.ejs
  views/register.ejs
  views/registered-now-login.ejs
  views/student-dashboard.ejs
  views/username-exists-login.ejs
Labels: bug, enhancement

#194 Implementation of the UI/UX Layout for the Chatroom
  app.js
  views/student-chatrooms.ejs
  views/student-dashboard.ejs
Labels: enhancement, Frontend

#198 confirmation and student evaluation page
  views/evaluation-confirmation.ejs
  views/student-evaluation.ejs
Labels: US.03

#200 Instructor Edit Teams
  views/create-teams.ejs
  views/edit-evaluation.ejs
  views/edit-team.ejs
Labels: enhancement, Frontend

#203 Feature/joyal detailed and summary review UI/ux
  views/username-exists-login.ejs
  views/view-reviews-detailed.ejs
  views/view-reviews-summary.ejs
Labels: enhancement, Stories, US.01, US.02, Frontend

#202 Create a View for Instructors Showing Completed Assessments
  app.js
  views/instructor-dashboard.ejs
  views/view-review-completion.ejs
Labels: enhancement, Frontend

#205 Summary detailed page
  .DS_Store
  app.js
  views/access-assessment.ejs
  views/instructor-dashboard.ejs
  views/peer-assessment.ejs
  views/view-review-completion.ejs
  views/view-reviews-detailed.ejs
  views/view-reviews-summary.ejs
Labels: enhancement, US.08

#211 Feautre/oussama UI view teams fixes
  .clj-kondo/.cache/v1/lock
  .lsp/.cache/db.transit.json
  views/access-assessment.ejs
  views/instructor-dashboard.ejs
  views/view-review-completion.ejs
  views/view-team-student.ejs
  views/view-teams-instructor.ejs
Labels: bug

#224 Feature/oussama notification
  app.js
  views/assess-notification.ejs
  views/student-dashboard.ejs
  views/view-reviews-summary.ejs
Labels: enhancement

#232 Sprint 4/joyal csvparsing
  .clj-kondo/.cache/v1/lock
  .lsp/.cache/db.transit.json
  app.js
  package-lock.json
  package.json
  views/create-profile.ejs
  views/edit-profile.ejs
  views/profile.ejs
Labels: bug, enhancement, Frontend, Backend

#243 commit change header
  views/partials/student-header.ejs
Labels: bug
