Repository SOEN341Fall2024/TeamXL-SOEN341_Project_F24, pull requests merged in 2024-10, with the labels that each got.

#69 Feature/joyal instructor team UI
  app.js
  views/create-teams.ejs
  views/instructor-dashboard.ejs
  views/student-dashboard.ejs
  views/view-teams-instructor.ejs
Labels: US.03, US.04

#83 Instructor: Create & Edit Teams UI
  app.js
  views/create-teams.ejs
  views/edit-team.ejs
Labels: US.02, US.05

#118 Student Peer Evaluation Page Implementation
  app.js
  views/student-dashboard.ejs
  views/student-evaluation.ejs
Labels: Stories, US.05

#121 Feature/oussama data post front
  .DS_Store
  views/student-evaluation.ejs
  views/username-exists-login.ejs
Labels: Stories, US.05

#125 created 2 new pages : thank you, evaluation cofirmation page.
  app.js
  views/evaluation-confirmation.ejs
  views/student-evaluation.ejs
  views/thank-you.ejs
Labels: Stories, US.06

#127 Student: UI/UX for View Reviews
  app.js
  views/peer-assessment.ejs
  views/student-dashboard.ejs
  views/view-reviews.ejs
Labels: enhancement, US.08

#134 Cancel button confirmation evaluation page.
  views/evaluation-confirmation.ejs
  views/thank-you.ejs
Labels: Stories, US.07

#137 Student: View Reviews page
  app.js
  views/student-dashboard.ejs
  views/view-my-reviews.ejs
  views/view-reviews.ejs
Labels: enhancement

#140 UI/UX for confirmation page and thank you page
  views/evaluation-confirmation.ejs
  views/student-evaluation.ejs
  views/thank-you.ejs
Labels: enhancement, Stories, US.06
